### ISSUE TITLE
How to init the Kubernetes client for the workspace backend

### ISSUE THREAD

**Issue by ederign** [kubeflow/notebooks#12]
### Checks

- [X] I have searched the [existing issues](https://github.com/kubeflow/notebooks/issues).

### Motivation

The goal of this issue is to develop: 
- backend k8s client (wrapper of kubernetes/client-go/) 

### Implementation

```
func NewKubernetesClient() (*KubernetesClient, error) {

	clientSet, err := newClientSet()
	if err != nil {
		return nil, fmt.Errorf("failed to create Kubernetes clientset: %w", err)
	}

	return &KubernetesClient{ClientSet: clientSet}, nil
}

func getRestConfig() (*restclient.Config, error) {
	loadingRules := clientcmd.NewDefaultClientConfigLoadingRules()
	configOverrides := &clientcmd.ConfigOverrides{}
	kubeConfig := clientcmd.NewNonInteractiveDeferredLoadingClientConfig(loadingRules, configOverrides)
	return kubeConfig.ClientConfig()
}

func newClientSet() (*kubernetes.Clientset, error) {
	restConfig, err := getRestConfig()
	if err != nil {
		return nil, err
	}
	return kubernetes.NewForConfig(restConfig)
}

```

### Are you willing & able to help?

- [X] I am able to submit a PR!
- [X] I can help test the feature!

**Comment by ederign** [comment]
FYI: I'm currently working on this. (I don't have 'assign' privileges yet).

**Comment by ederign** [comment]
Inside cluster:

```
> kubectl port-forward service/my-service-nb 8080:80
Forwarding from 127.0.0.1:8080 -> 4001
Forwarding from [::1]:8080 -> 4001
Handling connection for 8080
Handling connection for 8080
```
<img width="493" alt="image" src="https://github.com/kubeflow/notebooks/assets/531351/cc6543c7-cf06-4fe9-9ecf-35435fea95fb">


Outside cluster, you can either use .kube config OR export KUBECONFIG=pathtokubeconfig.yaml

**Comment by ederign** [comment]
Also, I've moved the Kubernetes client  to app startup. Seems like the Kubernetes client is designed to handle long-lived connections and can manage its own timeouts and retries.

However, on future, we can improve it with proper configuration of timeouts and other settings 

```
config.WrapTransport = func(rt http.RoundTripper) http.RoundTripper {
        return &http.Transport{
            Proxy:                 http.ProxyFromEnvironment,
            DialContext:           (&net.Dialer{Timeout: 30 * time.Second}).DialContext,
            TLSHandshakeTimeout:   10 * time.Second,
            ExpectContinueTimeout: 1 * time.Second,
            IdleConnTimeout:       90 * time.Second,
        }
    }
```

And also see if we should deal with refresh the client due to changes in the cluster configuration or credentials. But I believe we can approach both things in future.

**Comment by ederign** [comment]
@thesuperzapper one thing that I would like to discuss today!

**Comment by jiridanek** [comment]
I'm guessing this is how it works here

/priority p1
/assign @ederign

**Comment by jiridanek** [comment]
uh, sorry, I thought that `/help` will maybe display some help text for these commands ;P

/remove-help

**Comment by thesuperzapper** [comment]
I think we might be able to just use the `BuildConfigFromFlags` constructor directly with the `KUBECONFIG` env-var, like this:

```go
kubeconfig := os.Getenv("KUBECONFIG")
config, err = clientcmd.BuildConfigFromFlags("", kubeconfig)
if err != nil {
	return nil, fmt.Errorf("failed to load kubeconfig: %w", err)
}
```


Because the [upstream docs say](https://pkg.go.dev/k8s.io/client-go/tools/clientcmd#BuildConfigFromFlags) that `BuildConfigFromFlags()` will fallback to the default home location:

> BuildConfigFromFlags is a helper function that builds configs from a master url or a kubeconfig filepath. These are passed in as command line flags for cluster components. Warnings should reflect this usage. If neither masterUrl or kubeconfigPath are passed in we fallback to inClusterConfig. If inClusterConfig fails, we fallback to the default config.

So the flow would be:

1. Try reading KUBECONFIG, if that fails
2. Try in cluster, if that fails
3. Fall back to home directory

**Comment by thesuperzapper** [comment]
@ederign sorry, I was mistaken in https://github.com/kubeflow/notebooks/issues/12#issuecomment-2141051590.

The correct usage of the `clientcmd` package ([see here](https://github.com/kubernetes/client-go/blob/v0.30.1/tools/clientcmd/doc.go)) seems to be something like this:

```go
func getRestConfig() (*restclient.Config, error) {
	loadingRules := clientcmd.NewDefaultClientConfigLoadingRules()
	configOverrides := &clientcmd.ConfigOverrides{}
	kubeConfig := clientcmd.NewNonInteractiveDeferredLoadingClientConfig(loadingRules, configOverrides)
	return kubeConfig.ClientConfig()
}

func newClientSet() (*kubernetes.Clientset, error) {
	restConfig, err := getRestConfig()
	if err != nil {
		return nil, err
	}
	return kubernetes.NewForConfig(restConfig)
}
```

This combination of [`NewDefaultClientConfigLoadingRules`](https://github.com/kubernetes/client-go/blob/v0.30.1/tools/clientcmd/loader.go#L160) and [`NewNonInteractiveDeferredLoadingClientConfig`](https://github.com/kubernetes/client-go/blob/v0.30.1/tools/clientcmd/merged_client_builder.go#L53) cause the following order of precedence:

1. Try reading KUBECONFIG (splitting by `:` if there are multiple files specified in it).
2. Next, try using the default `$HOME/.kube/config` for the system.
3. Next, try using "in cluster config"
4. Fail otherwise

**Comment by ederign** [comment]
PR https://github.com/kubeflow/notebooks/pull/15/files
